# Generated by Django 6.0.3 on 2026-05-03 20:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='work_hours',
        ),
        migrations.RemoveField(
            model_name='companystore',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='company',
            name='main_work_hours',
            field=models.JSONField(default=api.models.get_default_work_hours),
        ),
        migrations.AddField(
            model_name='companystore',
            name='work_hours',
            field=models.JSONField(default=api.models.get_default_work_hours),
        ),
    ]
