# Generated by Django 6.0.3 on 2026-05-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_storelocation_mall_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='api.companystore'),
            preserve_default=False,
        ),
    ]
