# Generated by Django 6.0.3 on 2026-05-23 00:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_company_is_platinum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_work_days',
            field=models.JSONField(default=api.models.get_default_work_days),
        ),
        migrations.AddField(
            model_name='companystore',
            name='work_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
