# Generated by Django 6.0.3 on 2026-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_productlike_product_alter_productlike_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.IntegerField(choices=[(0, 'Nuevo pago recibido.'), (1, 'Pago aprobado.'), (2, 'Pago rechazado.'), (3, 'Suscripción expirada.'), (4, 'Nueva pregunta de cliente.'), (5, 'Nuevo pedido recibido.'), (6, 'Stock bajo de producto.'), (7, 'Producto agotado.'), (8, 'Reporte de métricas listo.'), (9, 'Alerta de tokens/gamificación.')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='section',
            field=models.IntegerField(choices=[(0, 'Home'), (1, 'Ordenes Cliente'), (2, 'Carrito'), (3, 'Buscador'), (4, 'Atlas'), (5, 'Ajustes'), (6, 'Ayuda'), (12, 'Suscripción Negocio'), (13, 'Mi Negocio'), (15, 'Inventario'), (28, 'Pedidos del Negocio'), (29, 'Preguntas al Vendedor'), (30, 'Analíticas'), (31, 'Gamificación'), (32, 'Empleados')]),
        ),
    ]
