# Generated by Django 6.0.3 on 2026-06-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_order_cancellation_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.IntegerField(choices=[(0, 'Nuevo pago recibido.'), (1, 'Pago aprobado.'), (2, 'Pago rechazado.'), (3, 'Suscripción expirada.'), (4, 'Nueva pregunta de cliente.'), (5, 'Nuevo pedido recibido.'), (6, 'Nueva respuesta recibida.'), (7, 'Stock bajo de producto.'), (8, 'Producto agotado.'), (9, 'Reporte de métricas listo.'), (10, 'Alerta de tokens/gamificación.'), (11, 'Actualización en orden.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Esperando'), (1, 'Delivery en camino'), (3, 'Cancelada'), (4, 'Completada'), (5, 'Resuelta')], default=0),
        ),
    ]
