# Generated by Django 6.0.3 on 2026-06-14 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVideoStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.CharField(blank=True, help_text='Ruta del video. Nulo si el medio ya expiró.', max_length=500, null=True)),
                ('thumbnail', models.CharField(blank=True, help_text='Ruta de la miniatura. Nulo si el medio ya expiró.', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Copy o descripción superpuesta.', null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Fecha límite de visibilidad pública del medio físico.')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Contador de popularidad.')),
                ('associated_item', models.ForeignKey(blank=True, help_text='Ítem de inventario vinculado al video para habilitar flujos de conversión directa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_stories', to='api.inventoryitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_stories', to='api.company')),
            ],
            options={
                'verbose_name': 'Video Historia de Compañía',
                'verbose_name_plural': 'Video Historias de Compañía',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='VideoEngagementLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('watch_time_seconds', models.FloatField(default=0.0, help_text='Tiempo acumulado neto de reproducción activa por parte del usuario.')),
                ('video_completed', models.BooleanField(default=False, help_text='Indica si el usuario completó la reproducción total del recurso.')),
                ('interacted_with_product', models.BooleanField(default=False, help_text='Indica si el cliente presionó el botón del producto vinculado.')),
                ('added_to_cart_from_video', models.BooleanField(default=False, help_text='Indica si la interacción derivó en una adición directa al carrito.')),
                ('bought_from_video', models.BooleanField(default=False, help_text='Indica si la visualización concluyó en una conversión de compra efectiva.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_engagement_records', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='api.companyvideostory')),
            ],
            options={
                'verbose_name': 'Log de Engagement de Video',
                'verbose_name_plural': 'Logs de Engagement de Video',
            },
        ),
    ]
