# Generated by Django 6.0.3 on 2026-06-15 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_companyvideostory_videoengagementlog'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productlike',
            name='user',
        ),
        migrations.AlterField(
            model_name='companyvideostory',
            name='associated_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_stories', to='api.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='companyvideostory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyvideostory',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='companyvideostory',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyvideostory',
            name='video_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyvideostory',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videoengagementlog',
            name='added_to_cart_from_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoengagementlog',
            name='bought_from_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoengagementlog',
            name='interacted_with_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoengagementlog',
            name='video_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoengagementlog',
            name='watch_time_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UniversalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('question_creation', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_creation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal_comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.DeleteModel(
            name='InventoryItemQuestion',
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
