# Generated by Django 6.0.3 on 2026-06-16 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_productlike_product_remove_productlike_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeviewlog',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='api.companystore'),
        ),
    ]
