# Generated by Django 6.0.3 on 2026-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_storeviewlog_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
