# Generated by Django 6.0.3 on 2026-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_inventoryitem_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvideostory',
            name='applied_filter_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
