# Generated by Django 6.0.3 on 2026-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_companyvideostory_applied_filter_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasplusplan',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Freemium'), (1, 'Premium')], default=0),
        ),
        migrations.AlterField(
            model_name='atlasplusplan',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
