# Generated by Django 6.0.3 on 2026-06-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_atlasplusplan_tier_alter_atlasplusplan_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasmessage',
            name='product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
