# Generated by Django 6.0.3 on 2026-06-21 22:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_atlasmessage_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='atlas_free_daily_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='atlas_plus_daily_limit',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='atlas_plus_price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.99'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='platinum_min_rating_promedy_requirement',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.5'), max_digits=12),
        ),
    ]
