# Generated by Django 6.0.3 on 2026-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_systemconfig_atlas_free_daily_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productviewlog',
            name='ai_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productviewlog',
            name='atlas_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productviewlog',
            name='origin_source',
            field=models.CharField(choices=[('organic', 'Orgánico'), ('atlas', 'Atlas IA')], default='organic', max_length=20),
        ),
        migrations.AddField(
            model_name='productviewlog',
            name='search_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
