# Generated by Django 6.0.3 on 2026-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_productviewlog_ai_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasmessage',
            name='action_command',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
