# Generated by Django 6.0.3 on 2026-06-22 16:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_atlasmessage_action_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmetDemandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(db_index=True, max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['coordinates'], name='unmet_demand_gis_idx', opclasses=['gist_geometry_ops_2d'])],
            },
        ),
    ]
