# Generated by Django 6.0.3 on 2026-06-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_unmetdemandlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvideostory',
            name='duration_seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
