# Generated by Django 6.0.3 on 2026-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_companyvideostory_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='platinum_min_sells_per_month_requirement',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventoryitemtransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso'), (2, 'Creacion')]),
        ),
        migrations.AlterField(
            model_name='tokenwallettransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso'), (2, 'Creacion')]),
        ),
    ]
