# Generated by Django 6.0.3 on 2026-06-25 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='conversation',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='topic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Nota de Voz')], default='text', max_length=10)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Enviando'), (1, 'Enviado al Servidor'), (2, 'Entregado al Dispositivo'), (3, 'Leído')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
