# Generated by Django 6.0.3 on 2026-06-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_supportticket_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='topic',
            field=models.IntegerField(choices=[(0, 'Problema con una Orden'), (1, 'Reclamo sobre Tienda'), (2, 'Problema con mi Cuenta'), (3, 'Otro')], default=3),
        ),
    ]
