# Generated by Django 6.0.3 on 2026-06-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_supportticket_close_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(0, 'Resuelto con éxito'), (1, 'No se pudo resolver'), (2, 'Spam / Inválido'), (3, 'El cliente no responde')], null=True),
        ),
    ]
