# Generated by Django 6.0.3 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_supportticket_close_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_check_payments',
            field=models.BooleanField(default=False, help_text='Puede ingresar al panel de pagos'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_check_support',
            field=models.BooleanField(default=False, help_text='Puede ingresar al panel de soporte'),
        ),
    ]
