# Generated by Django 6.0.3 on 2026-07-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_user_can_check_payments_user_can_check_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsubscription',
            name='notified_1_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantsubscription',
            name='notified_5_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantsubscription',
            name='notified_hours',
            field=models.BooleanField(default=False),
        ),
    ]
