# Generated by Django 6.0.3 on 2026-07-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merchantsubscription_notified_1_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_location',
            new_name='client_location',
        ),
    ]
