# Generated by Django 6.0.3 on 2026-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Nota de Voz')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enviando'), (1, 'Enviado al Servidor'), (2, 'Entregado al Dispositivo'), (3, 'Leído')], default=1),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
