# Generated by Django 6.0.3 on 2026-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_is_read_chatmessage_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
