# Generated by Django 6.0.3 on 2026-06-13 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_notification_category'),
        ('chat', '0003_alter_chatmessage_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_messages', to='api.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
