# Generated by Django 6.0.3 on 2026-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_predefinedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedmessage',
            name='title',
            field=models.CharField(default='Mensaje Rápido', max_length=100),
        ),
    ]
