# Generated by Django 6.0.3 on 2026-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_predefinedmessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedmessage',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
