# Generated by Django 6.0.3 on 2026-04-21 07:52

import colorfield.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.CharField(help_text='La imagen debe ser de 1920px x 1080px. Los primeros 180px de arriba estaran tapados por el AppBar del home.                                  Si la imagen esta en el servidor, solo especificar la ruta en la carpeta static, ej: static/img/banner_1_test.png', max_length=500)),
                ('navigate_to', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartMakerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(blank=True, choices=[(0, 'Banesco'), (1, 'Banco Mercantil'), (2, 'BBVA Provincial'), (3, 'Banco de Venezuela'), (4, 'Banco Exterior'), (5, 'Banco Nacional de Crédito'), (6, 'Banplus'), (7, 'Banco Digital de los Trabajadores'), (8, 'Sofitasa'), (9, 'Banco Plaza'), (10, 'Bancamiga')])),
                ('pago_movil_enabled', models.BooleanField(default=False)),
                ('tlf', models.CharField(blank=True)),
                ('document_number', models.CharField()),
                ('document_type', models.IntegerField(choices=[(0, 'CI'), (1, 'RIF')], default=0)),
                ('account_number', models.CharField()),
                ('active', models.BooleanField(default=True)),
                ('beneficiary_name', models.CharField(default='CODLINKER C.A')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.CharField(blank=True, help_text='Colocar ruta a traves del endpoint static del servidor. Ej: static/img/test.png', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('sold_out_time', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paused', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_capacity', models.IntegerField()),
                ('products_registration_with_ia', models.BooleanField(default=False)),
                ('profile_histories', models.BooleanField(default=False)),
                ('gamification_system', models.BooleanField(default=False)),
                ('gamification_analytics', models.BooleanField(default=False)),
                ('digital_performance_analytics', models.BooleanField(default=False)),
                ('clients_behavior_analytics', models.BooleanField(default=False)),
                ('operative_management_analytics', models.BooleanField(default=False)),
                ('company_branches', models.BooleanField(default=False)),
                ('company_employees', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False, help_text="Si está activo, mostrará el banner de 'POPULAR' y resaltará la tarjeta.")),
                ('short_description_html', models.TextField(blank=True, help_text='Descripción corta del plan. Sale en la tarjeta.')),
                ('large_description_html', models.TextField(blank=True, help_text='Descripción larga del plan. Sale en la pantalla de beneficios.')),
                ('warning_description_html', models.TextField(blank=True, help_text='Corta descripcion de requisitos indispensables. (Se ven de color rojo en la pantalla de beneficios)')),
                ('requires_business', models.BooleanField(default=False)),
                ('card_bg_color', colorfield.fields.ColorField(default='#E7E7E7', help_text='Color de fondo de la tarjeta', image_field=None, max_length=25, samples=None)),
                ('label_bg_color', colorfield.fields.ColorField(default='#B79DF0', help_text='Fondo de la etiqueta del nombre', image_field=None, max_length=25, samples=None)),
                ('label_border_color', colorfield.fields.ColorField(default='#6200EE', help_text='Borde de la etiqueta del nombre', image_field=None, max_length=25, samples=None)),
                ('label_text_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Color del texto de la etiqueta', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCancellationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platinum_min_rating_promedy_requirement', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nacionality', models.IntegerField(blank=True, choices=[(0, 'Venezolano'), (1, 'Extranjero')], default=None, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Cliente'), (1, 'Vendedor'), (2, 'Administrador')], default=0)),
                ('profile_picture', models.CharField(default='', max_length=500)),
                ('cedula_document', models.CharField(blank=True, max_length=500, null=True)),
                ('cedula_verified', models.BooleanField(default=False)),
                ('cedula_number', models.CharField(blank=True, max_length=50, null=True)),
                ('biometric_vector', pgvector.django.vector.VectorField(blank=True, dimensions=192, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino'), (2, 'No Binario')], default=0)),
                ('is_external_account', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', web.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AtlasPlusPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtlasPlusPlanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('payment_proof_url', models.URLField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bcv_taxes_to_day', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobada'), (2, 'Rechazada')], default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='web.atlasplusplan')),
            ],
        ),
        migrations.CreateModel(
            name='AtlasThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='web.atlasplusplan')),
            ],
        ),
        migrations.CreateModel(
            name='AtlasMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(choices=[(0, 'Cliente'), (1, 'Atlas')])),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.atlasthread')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.IntegerField(choices=[(0, 'Instagram'), (1, 'Whatsapp'), (2, 'Llamada')])),
                ('value', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.companycategory')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('business_hours', models.JSONField(default=dict)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='web.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_inventory', models.BooleanField(default=False)),
                ('can_view_sales', models.BooleanField(default=False)),
                ('can_manage_orders', models.BooleanField(default=True)),
                ('allowed_stores', models.ManyToManyField(blank=True, related_name='assigned_employees', to='web.companystore')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='web.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.companystore')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField()),
                ('percentage', models.IntegerField()),
                ('product_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='web.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_creation', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_creation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='web.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('transaction_type', models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso')])),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='web.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califications', to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_until', models.DateTimeField(default=None, null=True)),
                ('merchant_type', models.IntegerField(choices=[(0, 'Emprendedor'), (1, 'Empresa')])),
                ('rif_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.merchantplan')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPlanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('payment_proof_url', models.URLField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bcv_taxes_to_day', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobada'), (2, 'Rechazada')], default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='web.merchantsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.JSONField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Esperando'), (3, 'Cancelada'), (4, 'Completada'), (5, 'Resuelta')], default=0)),
                ('withdrawal_type', models.IntegerField(choices=[(0, 'En tienda'), (1, 'Delivery')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='web.companystore')),
                ('cancellation_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.ordercancellationtopic')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('discounts_by_tokens_active', models.BooleanField(default=False)),
                ('discounts_data', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web.company')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='web.product'),
        ),
        migrations.CreateModel(
            name='ProductCalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califications', to='web.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_to_cart', models.BooleanField(default=False)),
                ('bought', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='web.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califications', to='web.companystore')),
            ],
        ),
        migrations.CreateModel(
            name='StoreContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.IntegerField(choices=[(0, 'Instagram'), (1, 'Whatsapp'), (2, 'Llamada')])),
                ('value', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='web.companystore')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='web.companystore')),
            ],
        ),
        migrations.CreateModel(
            name='StoreViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('location_watched', models.BooleanField(default=False)),
                ('presentation_video_watched', models.BooleanField(default=False)),
                ('stories_watched', models.BooleanField(default=False)),
                ('products_watched', models.BooleanField(default=False)),
                ('tryed_to_contact', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.CharField(blank=True, help_text='Colocar ruta a traves del endpoint static del servidor. Ej: static/img/test.png', null=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='web.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subcategory'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('conversation', models.JSONField(default=list)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('waiting_for_client_reply', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_wallets', to='web.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso')])),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.order')),
                ('token_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='web.tokenwallet')),
            ],
        ),
        migrations.CreateModel(
            name='UserNavigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_record', models.JSONField(default=dict)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['biometric_vector'], m=16, name='user_biometric_hsnw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='employeestoreassignment',
            unique_together={('employee', 'store')},
        ),
    ]
