# Generated by Django 6.0.3 on 2026-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplusplanpayment',
            name='payment_proof_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companystore',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanpayment',
            name='payment_proof_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchantsubscription',
            name='company_document_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
