# Generated by Django 6.0.3 on 2026-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystore',
            name='image',
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
