# Generated by Django 6.0.3 on 2026-04-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_atlasplusplanpayment_payment_proof_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasplusplanpayment',
            name='rejection_reason',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='merchantplanpayment',
            name='rejection_reason',
            field=models.CharField(blank=True, default=''),
        ),
    ]
