# Generated by Django 6.0.3 on 2026-05-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_companystore_image_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gamification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='gamification_tokens_per_dollar',
            field=models.IntegerField(default=0),
        ),
    ]
