# Generated by Django 6.0.3 on 2026-05-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_company_gamification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='work_hours',
            field=models.JSONField(default={'end': '06:30 PM', 'start': '08:00 AM'}),
        ),
    ]
