# Generated by Django 6.0.3 on 2026-04-22 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_atlasplusplanpayment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasplusplanpayment',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantplanpayment',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
