# Generated by Django 6.0.3 on 2026-04-22 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_atlasplusplanpayment_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantsubscription',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
