# Generated by Django 6.0.3 on 2026-05-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_company_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='presentation_video_url',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='companystore',
            name='store_img_url',
            field=models.CharField(default=None, null=True),
        ),
    ]
