# Generated by Django 6.0.3 on 2026-05-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_company_presentation_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='presentation_video_thumbnail',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companystore',
            name='store_type',
            field=models.IntegerField(choices=[(0, 'En centro comercial'), (1, 'Local a pie de calle'), (2, 'Kiosco'), (3, 'Oficina'), (4, 'Tienda virtual'), (5, 'Unidad móvil / Food Truck'), (6, 'Puesto buhonero')], default=1),
        ),
        migrations.AddConstraint(
            model_name='storecontactmethod',
            constraint=models.UniqueConstraint(fields=('store', 'method_type'), name='unique_contact_method_per_store'),
        ),
    ]
