# Generated by Django 6.0.3 on 2026-04-22 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_atlasplusplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplusplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
