# Generated by Django 6.0.3 on 2026-05-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_company_presentation_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='mall_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
