# Generated by Django 6.0.3 on 2026-04-23 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_atlasplusplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlasplusplan',
            name='is_active',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(choices=[(0, 'Home'), (1, 'Ordenes'), (2, 'Carrito'), (3, 'Buscador'), (4, 'Atlas'), (5, 'Ayuda'), (6, 'Ajustes')])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(0, 'Nuevo pago recibido.'), (1, 'Pago aprobado.'), (2, 'Pago rechazado.'), (3, 'Suscripción expirada.')])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
