# Generated by Django 6.0.3 on 2026-04-24 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_merchantplanpayment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsubscription',
            name='adquired_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
