# Generated by Django 6.0.3 on 2026-05-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_inventoryitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlocation',
            name='description',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
