# Generated by Django 6.0.3 on 2026-04-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_merchantsubscription_adquired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantplanpayment',
            name='rejection_help',
            field=models.IntegerField(blank=True, choices=[(1, 'El número de referencia ingresado no coincide con nuestros registros bancarios. Por favor, verifique los dígitos y vuelva a intentarlo.'), (2, 'El monto verificado es menor al costo del plan seleccionado. Asegúrese de transferir el monto exacto incluyendo comisiones si aplican.'), (3, 'La fecha indicada en el formulario no coincide con la del comprobante. Por favor, seleccione la fecha exacta en la que realizó la operación.'), (4, 'La imagen adjunta no es legible, está borrosa o no corresponde a un comprobante válido. Suba una captura de pantalla clara donde se vean todos los datos de la operación.'), (5, 'Su pago ha sido rechazado por un motivo no listado. Por favor, póngase en contacto con soporte técnico para más detalles.')], null=True),
        ),
    ]
