# Generated by Django 6.0.3 on 2026-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_clientlocation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_platinum',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es True, la empresa tiene +4.5 estrellas y alto volumen de ventas. Recibe boost en el motor de búsqueda.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cached_popularity_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Puntuación precalculada de interacciones (visitas, carritos, compras). Evita JOINs masivos. Usado por el motor de busqueda.'),
        ),
    ]
