# Generated by Django 6.0.3 on 2026-04-25 03:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_atlasplusplanpayment_rejection_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplusplanpayment',
            name='rejection_help',
            field=models.IntegerField(blank=True, choices=[(1, 'El número de referencia ingresado no coincide con nuestros registros bancarios. Por favor, verifique los dígitos y vuelva a intentarlo.'), (2, 'La fecha indicada en el formulario no coincide con la del comprobante. Por favor, seleccione la fecha exacta en la que realizó la operación.'), (3, 'La imagen adjunta no es legible, está borrosa o no corresponde a un comprobante válido. Suba una captura de pantalla clara donde se vean todos los datos de la operación.'), (4, 'Su pago ha sido rechazado por un motivo no listado. Por favor, póngase en contacto con soporte técnico para más detalles.')], null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanpayment',
            name='rejection_help',
            field=models.IntegerField(blank=True, choices=[(1, 'El número de referencia ingresado no coincide con nuestros registros bancarios. Por favor, verifique los dígitos y vuelva a intentarlo.'), (2, 'La fecha indicada en el formulario no coincide con la del comprobante. Por favor, seleccione la fecha exacta en la que realizó la operación.'), (3, 'La imagen adjunta no es legible, está borrosa o no corresponde a un comprobante válido. Suba una captura de pantalla clara donde se vean todos los datos de la operación.'), (4, 'Su pago ha sido rechazado por un motivo no listado. Por favor, póngase en contacto con soporte técnico para más detalles.')], null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanpayment',
            name='rejection_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Referencia inválida o no encontrada'), (2, 'Fecha de transferencia incorrecta'), (3, 'Comprobante falso o ilegible'), (4, 'Otro motivo no especificado')], null=True),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('history', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
