# Generated by Django 6.0.3 on 2026-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_atlasplusplanpayment_rejection_help_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplusplanpayment',
            name='rejection_help',
            field=models.IntegerField(blank=True, choices=[(1, 'El número de referencia ingresado no coincide con nuestros registros bancarios. Por favor, verifique los dígitos y vuelva a intentarlo.'), (2, 'La fecha indicada en el formulario no coincide con la del comprobante. Por favor, seleccione la fecha exacta en la que realizó la operación.'), (3, 'La imagen adjunta no es legible, está borrosa o no corresponde a un comprobante válido. Suba una captura de pantalla clara donde se vean todos los datos de la operación.'), (4, 'Su pago ha sido rechazado por un motivo no listado. Por favor, póngase en contacto con soporte técnico para más detalles.'), (5, 'Su pago ha sido abonado a su cuenta. Por favor, realice el reporte de pago del monto restante para continuar con la activación de su suscripción.')], null=True),
        ),
        migrations.AlterField(
            model_name='atlasplusplanpayment',
            name='rejection_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Referencia inválida o no encontrada'), (2, 'Fecha de transferencia incorrecta'), (3, 'Comprobante falso o ilegible'), (4, 'Otro motivo no especificado'), (5, 'Monto incompleto')], null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanpayment',
            name='rejection_help',
            field=models.IntegerField(blank=True, choices=[(1, 'El número de referencia ingresado no coincide con nuestros registros bancarios. Por favor, verifique los dígitos y vuelva a intentarlo.'), (2, 'La fecha indicada en el formulario no coincide con la del comprobante. Por favor, seleccione la fecha exacta en la que realizó la operación.'), (3, 'La imagen adjunta no es legible, está borrosa o no corresponde a un comprobante válido. Suba una captura de pantalla clara donde se vean todos los datos de la operación.'), (4, 'Su pago ha sido rechazado por un motivo no listado. Por favor, póngase en contacto con soporte técnico para más detalles.'), (5, 'Su pago ha sido abonado a su cuenta. Por favor, realice el reporte de pago del monto restante para continuar con la activación de su suscripción.')], null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanpayment',
            name='rejection_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Referencia inválida o no encontrada'), (2, 'Fecha de transferencia incorrecta'), (3, 'Comprobante falso o ilegible'), (4, 'Otro motivo no especificado'), (5, 'Monto incompleto')], null=True),
        ),
    ]
