# Generated by Django 6.0.3 on 2026-06-08 23:30

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_notification_category_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='companystore',
            name='is_main_store',
            field=models.BooleanField(default=False, help_text='Indica si es la sucursal principal. Obligatorio si el plan no permite múltiples sucursales.'),
        ),
        migrations.AlterField(
            model_name='atlasplusplanpayment',
            name='rejection_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Referencia inválida o no encontrada'), (2, 'Fecha de transferencia incorrecta'), (3, 'Comprobante falso o ilegible'), (5, 'Monto incompleto'), (4, 'Otro motivo no especificado')], null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanpayment',
            name='rejection_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Referencia inválida o no encontrada'), (2, 'Fecha de transferencia incorrecta'), (3, 'Comprobante falso o ilegible'), (5, 'Monto incompleto'), (4, 'Otro motivo no especificado')], null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.IntegerField(choices=[(0, 'Nuevo pago recibido.'), (1, 'Pago aprobado.'), (2, 'Pago rechazado.'), (3, 'Suscripción expirada.'), (4, 'Nueva pregunta de cliente.'), (5, 'Nuevo pedido recibido.'), (6, 'Nueva respuesta recibida.'), (7, 'Stock bajo de producto.'), (8, 'Producto agotado.'), (9, 'Reporte de métricas listo.'), (10, 'Alerta de tokens/gamificación.')]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='product_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='companystore',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_store', True)), fields=('company',), name='unique_main_store_per_company'),
        ),
    ]
