# Generated by Django 6.0.3 on 2026-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_merchantplanpayment_target_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_topic',
            field=models.IntegerField(blank=True, choices=[(1, 'Encontré un mejor precio.'), (2, 'Me equivoqué de producto.'), (3, 'El delivery tarda demasiado.'), (4, 'Ya no lo necesito.'), (5, 'Otros motivos.')], null=True),
        ),
        migrations.DeleteModel(
            name='StoreCalification',
        ),
    ]
