"""
Django settings for cartmaker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from .enviroment_manager import EnviromentManager
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
import firebase_admin
from firebase_admin import credentials
import os
from celery.schedules import crontab

env_manager = EnviromentManager()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_manager.DJANGO_SECRET_KEY
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_manager.DEBUG

DOMAIN = env_manager.DOMAIN

# settings.py
if DEBUG:
    # Evita que WhiteNoise intente comprimir o manifestar archivos en cada request
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.gis',
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.postgres',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    "colorfield",
    'api',
    'chat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cartmaker_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cartmaker_admin.wsgi.application'


# Configuración global de DRF
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth': '5/minute', # Para registro, login.
        'navigation': '30/minute', # Para navegacion entre vistas.
        'actions': '50/minute', # Para visualizacion de productos.
        'anti_bots':"1/second",
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CartMaker API',
    'DESCRIPTION': 'Documentación oficial del backend de CartMaker.',
    'VERSION': env_manager.API_VERSION,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env_manager.JWT_SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': env_manager.DB_NAME,
        'USER': env_manager.DB_USER,
        'PASSWORD': env_manager.DB_PASSWORD,
        'HOST': env_manager.DB_HOST,
        'PORT': env_manager.DB_PORT,
    }
}

AUTH_USER_MODEL = 'api.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'


LANGUAGES = (
    ("es", _("Spanish")),
    ("en", _("English"))
)

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    # BASE_DIR / "static", 
]
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Unfold (Panel de admin moderno)

USE_I18N = True

UNFOLD = {
    "SITE_TITLE": "Admin | CartMaker",
    "SITE_HEADER": "CartMaker Core",
    "SITE_SUBHEADER": "Panel de Administración Central",
    "SITE_LOGO": {
        "light": lambda request: static("img/logo.svg"),  # Asegúrate de tener tu logo
        "dark": lambda request: static("img/logo.svg"),
    },
    "SITE_SYMBOL": "speed",  # Ícono alternativo si no carga el logo
    "SITE_URL": "/",
    
    # 💡 INYECCIÓN DE MARCA: Tonos Morados de CartMaker
    "COLORS": {
        "primary": {
            "50": "#faf5ff",
            "100": "#f3e8ff",
            "200": "#e9d5ff",
            "300": "#d8b4fe",
            "400": "#c084fc",
            "500": "#a855f7", # Morado CartMaker
            "600": "#9333ea",
            "700": "#7e22ce",
            "800": "#6b21a8",
            "900": "#581c87",
            "950": "#3b0764",
        },
    },
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, # Mantiene el menú limpio
        "navigation": [
            {
                "title": "Usuarios y Accesos",
                "separator": True, # Agrega una línea divisoria visual
                "items": [
                    {"title": "Usuarios", "link": "/admin/api/user/", "icon": "group"},
                    {"title": "Billeteras (Fiat)", "link": "/admin/api/userwallet/", "icon": "account_balance_wallet"},
                    {"title": "Notificaciones", "link": "/admin/api/notification/", "icon": "notifications_active"},
                    {"title": "Ubicaciones (Clientes)", "link": "/admin/api/clientlocation/", "icon": "pin_drop"},
                    {"title": "Métodos de contacto", "link": "/admin/api/clientcontactmethod/", "icon": "contact_phone"},
                    {"title": "Dispositivos Móviles", "link": "/admin/api/devicetoken/", "icon": "phonelink_setup"}
                ],
            },
            {
                "title": "Estructura Comercial",
                "separator": True,
                "items": [
                    {"title": "Compañías", "link": "/admin/api/company/", "icon": "corporate_fare"},
                    {"title": "Categorías de Negocio", "link": "/admin/api/companycategory/", "icon": "domain"},
                    {"title": "Sucursales", "link": "/admin/api/companystore/", "icon": "storefront"},
                    {"title": "Centros Comerciales", "link": "/admin/api/mall/", "icon": "local_mall"},
                    {"title": "Ubicaciones (Tiendas)", "link": "/admin/api/storelocation/", "icon": "share_location"},
                    {"title": "Directorio de Contacto", "link": "/admin/api/storecontactmethod/", "icon": "support_agent"},
                    {"title": "Personal y Empleados", "link": "/admin/api/employee/", "icon": "badge"},
                    {"title": "Roles y Permisos", "link": "/admin/api/employeepermission/", "icon": "security"},
                    {"title": "Asignación de Sucursal", "link": "/admin/api/employeestoreassignment/", "icon": "assignment_ind"}
                ],
            },
            {
                "title": "Catálogo e Inventario",
                "separator": True,
                "items": [
                    {"title": "Categorías", "link": "/admin/api/category/", "icon": "grid_view"},
                    {"title": "Sub-Categorías", "link": "/admin/api/subcategory/", "icon": "segment"},
                    {"title": "Productos Maestros", "link": "/admin/api/product/", "icon": "inventory_2"},
                    {"title": "Existencias (Lotes)", "link": "/admin/api/inventoryitem/", "icon": "view_in_ar"},
                    {"title": "Ofertas Activas", "link": "/admin/api/inventoryitemoffer/", "icon": "loyalty"},
                    {"title": "Auditoría de Stock", "link": "/admin/api/inventoryitemtransaction/", "icon": "sync_alt"},
                ],
            },
            {
                "title": "Ventas y Fidelización",
                "separator": True,
                "items": [
                    {"title": "Órdenes de Compra", "link": "/admin/api/order/", "icon": "local_shipping"},
                    {"title": "Motivos de Cancelación", "link": "/admin/api/ordercancellationtopic/", "icon": "rule"},
                    {"title": "Billeteras de Tokens", "link": "/admin/api/tokenwallet/", "icon": "savings"},
                    {"title": "Emisión de Tokens", "link": "/admin/api/tokenwallettransaction/", "icon": "receipt_long"},
                ]
            },
            {
                "title": "Red Social y Multimedia",
                "separator": True,
                "items": [
                    {"title": "Video Historias", "link": "/admin/api/companyvideostory/", "icon": "video_library"},
                    {"title": "Q&A (Dudas Públicas)", "link": "/admin/api/universalcomment/", "icon": "forum"},
                    {"title": "Likes (Me Gusta)", "link": "/admin/api/universallike/", "icon": "thumb_up"},
                ]
            },
            {
                "title": "Reputación y Soporte",
                "separator": True,
                "items": [
                    {"title": "Reviews: Tiendas", "link": "/admin/api/storecalification/", "icon": "store"},
                    {"title": "Reviews: Productos", "link": "/admin/api/productcalification/", "icon": "star"},
                    {"title": "Reviews: Comerciantes", "link": "/admin/api/merchantcalification/", "icon": "workspace_premium"},
                    {"title": "Tickets de Soporte", "link": "/admin/api/supportticket/", "icon": "headset_mic"},
                ]
            },
            {
                "title": "Suscripciones (B2B)",
                "separator": True,
                "items": [
                    {"title": "Planes de Negocio", "link": "/admin/api/merchantplan/", "icon": "card_membership"},
                    {"title": "Suscripciones Activas", "link": "/admin/api/merchantsubscription/", "icon": "verified"},
                    {"title": "Pagos Recibidos", "link": "/admin/api/merchantplanpayment/", "icon": "price_check"},
                ]
            },
            {
                "title": "Inteligencia Artificial (Atlas)",
                "separator": True,
                "items": [
                    {"title": "Suscripciones Atlas+", "link": "/admin/api/atlasplusplan/", "icon": "auto_awesome"},
                    {"title": "Pagos Atlas+", "link": "/admin/api/atlasplusplanpayment/", "icon": "payments"},
                    {"title": "Hilos de Conversación", "link": "/admin/api/atlasthread/", "icon": "memory"},
                    {"title": "Log de Mensajes IA", "link": "/admin/api/atlasmessage/", "icon": "chat_bubble"},
                ],
            },
            {
                "title": "Telemetría y Data Lake",
                "separator": True,
                "items": [
                    {"title": "Tráfico de Vistas (Productos)", "link": "/admin/api/productviewlog/", "icon": "touch_app"},
                    {"title": "Tráfico de Visitas (Tiendas)", "link": "/admin/api/storeviewlog/", "icon": "visibility"},
                    {"title": "Retención de Video", "link": "/admin/api/videoengagementlog/", "icon": "monitoring"},
                    {"title": "Rutas de Navegación", "link": "/admin/api/usernavigationlog/", "icon": "timeline"},
                ]
            },
            {
                "title": "Ajustes Core",
                "separator": True,
                "items": [
                    {"title": "Cuentas Receptoras", "link": "/admin/api/cartmakerbankaccount/", "icon": "account_balance"},
                    {"title": "Anuncios Globales", "link": "/admin/api/announcement/", "icon": "campaign"},
                    {"title": "Parámetros del Sistema", "link": "/admin/api/systemconfig/", "icon": "settings_suggest"},
                ]
            },
        ],
    },
}

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # DB 1 exclusiva para caché de la app
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# CELERY Y REDIS
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Caracas' 
CELERY_ENABLE_UTC = False

CELERY_BEAT_SCHEDULE = {
    # Tarea 1: Limpiar ofertas de descuento expiradas en items. Todos los días a las 12:02 AM
    'cleanup-expired-offers-midnight': {
        'task': 'api.tasks.cleanup_expired_offers', 
        'schedule': crontab(minute=2, hour=0), 
    },
    
    # Tarea 2: Evaluar comerciantes Platinum. Todos los días a las 3:00 AM
    'evaluate-platinum-status-nightly': {
        'task': 'api.tasks.evaluate_platinum_status', 
        'schedule': crontab(minute=0, hour=3), 
    },
    
    # Tarea 3: Alerta de órdenes estancadas. Revisa y notifica al vendedor cada 6 horas en punto
    'send-merchant-order-reminders-every-6h': {
        'task': 'cartmaker.orders.send_merchant_reminders',  # 💡 Nombre explícito del decorador
        'schedule': crontab(minute=0, hour='*/6'),          # '*/6' ejecuta a las 00:00, 06:00, 12:00 y 18:00
    },
    
    # Tarea 4: Limpieza de almacenamiento de videos e historias expiradas (72h). Corre al inicio de cada hora
    'cleanup-expired-video-stories-hourly': {
        'task': 'api.tasks.cleanup_expired_video_stories', 
        'schedule': crontab(minute=0),                      # Al omitir 'hour', corre en el minuto 0 de cada hora
    },
}

# FIREBASE
path_to_json = os.path.join(BASE_DIR, '.', 'firebase-adminsdk.json')
cred = credentials.Certificate(path_to_json)
firebase_admin.initialize_app(cred)

# CREDENCIALES PARA SERVICIOS DE TERCEROS
GOOGLE_OAUTH_CLIENT_ID=env_manager.GOOGLE_OAUTH_CLIENT_ID
GOOGLE_MAPS_API_KEY=env_manager.GOOGLE_MAPS_API_KEY
STORAGE_TYPE=env_manager.STORAGE_TYPE

AWS_ACCESS_KEY_ID = env_manager.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = env_manager.AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = env_manager.AWS_STORAGE_BUCKET_NAME
AWS_S3_REGION_NAME = env_manager.AWS_S3_REGION_NAME
AWS_MEDIACONVERT_ROLE_ARN = env_manager.AWS_MEDIACONVERT_ROLE_ARN

CEDULAS_API_APP_ID = env_manager.CEDULAS_API_APP_ID
CEDULAS_API_ACCESS_TOKEN = env_manager.CEDULAS_API_ACCESS_TOKEN
USE_CEDULAS_API = env_manager.USE_CEDULAS_API

GEMINI_API_KEY = env_manager.GEMINI_API_KEY
OPENROUTER_API_KEY = env_manager.OPENROUTER_API_KEY