"""
Django settings for cartmaker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from .enviroment_manager import EnviromentManager
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
import firebase_admin
from firebase_admin import credentials
import os

env_manager = EnviromentManager()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_manager.DJANGO_SECRET_KEY
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_manager.DEBUG

DOMAIN = env_manager.DOMAIN

# settings.py
if DEBUG:
    # Evita que WhiteNoise intente comprimir o manifestar archivos en cada request
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.gis',
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.postgres',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    "colorfield",
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cartmaker_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cartmaker_admin.wsgi.application'


# Configuración global de DRF
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth': '5/minute', # Para registro, login.
        'navigation': '30/minute', # Para navegacion entre vistas.
        'actions': '50/minute', # Para visualizacion de productos.
        'anti_bots':"1/second",
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CartMaker API',
    'DESCRIPTION': 'Documentación oficial del backend de CartMaker.',
    'VERSION': env_manager.API_VERSION,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env_manager.JWT_SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': env_manager.DB_NAME,
        'USER': env_manager.DB_USER,
        'PASSWORD': env_manager.DB_PASSWORD,
        'HOST': env_manager.DB_HOST,
        'PORT': env_manager.DB_PORT,
    }
}

AUTH_USER_MODEL = 'web.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'


LANGUAGES = (
    ("es", _("Spanish")),
    ("en", _("English"))
)

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    # BASE_DIR / "static", 
]
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Unfold (Panel de admin moderno)

USE_I18N = True

UNFOLD = {
    "SITE_TITLE": "Administracion",
    "SITE_HEADER": "Administracion de CartMaker",
    "SITE_SUBHEADER": "Cart Maker",
    "SITE_LOGO": {
        "light": lambda request: static("img/logo.svg"),
        "dark": lambda request: static("img/logo.svg"),
    },
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Manejo de Usuarios",
                "items": [
                    {"title": "Usuarios", "link": "/admin/web/user/", "icon": "account_circle"},
                    {'title': "Billeteras", "link":'/admin/web/userwallet/', "icon":"wallet"},
                    {"title": "Notificaciones", "link": "/admin/web/notification/", "icon": "notification_important"},
                    {"title":"Ubicaciones", "link":"/admin/web/clientlocation/", "icon":"location_on"},
                    {'title':"Métodos de contacto", "link":"/admin/web/clientcontactmethod/", "icon":"call"},
                    {'title':"Dispositivos registrados", "link":"/admin/web/devicetoken/", "icon":"phone"}
                ],
            },
            {
                "title": "Estructura Comercial",
                "items": [
                    {"title": "Compañías", "link": "/admin/web/company/", "icon": "business"},
                    {"title":"Categorías", 'link':"/admin/web/companycategory/", "icon":"domain_disabled"},
                    {"title": "Tiendas", "link": "/admin/web/companystore/", "icon": "storefront"},
                    {"title": "Ubicaciones", "link":"/admin/web/storelocation/", "icon":"location_on"},
                    {"title": "Métodos de contacto", "link":"/admin/web/storecontactmethod/", "icon":"call"},
                    {"title":"Empleados", "link":"/admin/web/employee/", "icon":"emoji_people"},
                    {"title":"Permisos de empleados", "link":"/admin/web/employeepermission/", "icon":"manage_accounts"},
                    {"title":"Asignaciones empleado-sucursal", "link":"/admin/web/employeestoreassignment/", "icon":"add_home_work"}
                ],
            },
            {
                "title": "Productos e Inventario",
                "items": [
                    {"title":"Categorías", 'link':"/admin/web/category/", "icon":"category"},
                    {"title":"Sub-Categorías", 'link':"/admin/web/subcategory/", "icon":"category_search"},
                    {"title": "Productos", "link": "/admin/web/product/", "icon": "inventory_2"},
                    {"title": "Items en inventario", "link":"/admin/web/inventoryitem/", "icon":"box"},
                    {"title":"Ofertas en items", "link":"/admin/web/inventoryitemoffer/", "icon":"percent_discount"},
                    {"title":"Transacciones de items", "link":"/admin/web/inventoryitemtransaction/", "icon":"arrows_left_right_circle"},
                    {"title":"Preguntas de clientes", "link":"/admin/web/inventoryitemquestion/", "icon":"contact_support"},
                ],
            },
            {
                "title":"Ventas y Fidelización",
                "items":[
                    {"title": "Topicos de cancelación de órdenes", "link": "/admin/web/ordercancellationtopic/", "icon": "cancel"},
                    {"title": "Órdenes", "link": "/admin/web/order/", "icon": "shopping_cart"},
                    {"title": "Billeteras de tokens", "link":"/admin/web/tokenwallet/", "icon":"wallet"},
                    {"title": "Movimientos de billeteras", "link":"/admin/web/tokenwallettransaction", "icon":"payments"},
                ]
            },
            {
                "title":"Calificación y Soporte",
                "items":[
                    {"title":"Calificaciones de tiendas", "link":"/admin/web/storecalification/", "icon":"star_rate"},
                    {"title":"Calificaciones de productos", "link":"/admin/web/productcalification/", "icon":"star_rate"},
                    {"title":"Calificaciones de comerciantes", "link":"/admin/web/merchantcalification/", "icon":"star_rate"},
                    {"title":"Tickets de soporte", "link":"/admin/web/supportticket/", "icon":"support_agent"},
                ]
            },
            {
                "title":"Suscripciones y Planes",
                "items":[
                    {'title':'Planes de comerciantes', "link":"/admin/web/merchantplan/", "icon":"id_card"},
                    {'title':"Suscripciones de comerciantes", "link":"/admin/web/merchantsubscription", "icon":"credit_score"},
                    {"title":'Pagos de planes', "link":"/admin/web/merchantplanpayment", "icon":"price_check"},
                ]
            },
            {
                "title": "Atlas IA",
                "items": [
                    {"title": "Suscripciones a Atlas Plus", "link": "/admin/web/atlasplusplan/", "icon": "credit_score"},
                    {"title": "Pagos a Atlas Plus", "link": "/admin/web/atlasplusplanpayment/", "icon": "price_check"},
                    {"title": "Conversaciones con Atlas", "link":"/admin/web/atlasthread/", "icon":"comment"},
                    {"title": "Mensajes en Atlas", "link":"/admin/web/atlasmessage/", "icon":"chat"},
                ],
            },
            {
                "title":"Configuración y Anuncios",
                "items":[
                    {'title':'Cuentas bancarias de CartMaker', 'link':"/admin/web/cartmakerbankaccount", "icon":"account_balance"},
                    {'title':"Configuración del sistema", "link":"/admin/web/systemconfig/", "icon":"settings"},
                    {"title":"Anuncios", "link":"/admin/web/announcement/", "icon":"brand_awareness"}
                ]
            },
            {
                "title":"Logs y Estadísticas",
                "items":[
                    {'title':"Navegaciones", "link":"/admin/web/usernavigationlog/", "icon":"navigation"},
                    {'title':"Ojeos a tiendas", "link":"/admin/web/storeviewlog/", 'icon':'store'},
                    {'title':'Ojeos a productos', "link":"/admin/web/productviewlog/", "icon":'feature_search'}
                ]
            }
        ],
    },
}

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'cartmaker-cache',
    }
}

# CELERY Y REDIS
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# FIREBASE
path_to_json = os.path.join(BASE_DIR, '.', 'firebase-adminsdk.json')
cred = credentials.Certificate(path_to_json)
firebase_admin.initialize_app(cred)

# CREDENCIALES PARA SERVICIOS DE TERCEROS
GOOGLE_OAUTH_CLIENT_ID=env_manager.GOOGLE_OAUTH_CLIENT_ID
GOOGLE_MAPS_API_KEY=env_manager.GOOGLE_MAPS_API_KEY
STORAGE_TYPE=env_manager.STORAGE_TYPE

AWS_ACCESS_KEY_ID = env_manager.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = env_manager.AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = env_manager.AWS_STORAGE_BUCKET_NAME
AWS_S3_REGION_NAME = env_manager.AWS_S3_REGION_NAME

CEDULAS_API_APP_ID = env_manager.CEDULAS_API_APP_ID
CEDULAS_API_ACCESS_TOKEN = env_manager.CEDULAS_API_ACCESS_TOKEN
USE_CEDULAS_API = env_manager.USE_CEDULAS_API